# frozen_string_literal: true

# SisyphusWorker: Autonomous execution agent that executes structured plans step-by-step.
# Named after the Greek hero condemned to eternally push a boulder uphill, Sisyphus
# processes ExecutionPlan objects generated by PlanAgentWorker, executing actions,
# evaluating completion, and tracking all changes with Git checkpoints.
#
# Unlike Cline's synchronous approval model, Sisyphus operates autonomously by default
# but can be configured for step-by-step or milestone-by-milestone approval.
#
# @example Basic autonomous execution
#   worker = SisyphusWorker.new(
#     execution_plan: plan,
#     path: "/path/to/codebase",
#     config: { approval_mode: :autonomous }
#   )
#   result = worker.execute
#
# @example With step-by-step approval
#   worker = SisyphusWorker.new(
#     execution_plan: plan,
#     path: "/path/to/codebase",
#     config: { approval_mode: :step, max_retries: 3 }
#   )
#   result = worker.execute
#
class SisyphusWorker < BaseWorker
  # Sisyphus-specific states beyond base worker states
  initial_state :pending

  state :pending,           description: "Worker created, not yet started"
  state :running,           description: "Initializing execution"
  state :executing,         description: "Executing plan steps"
  state :evaluating,        description: "Evaluating step completion"
  state :checkpoint_created, description: "Created milestone checkpoint"
  state :error_recovery,    description: "Recovering from error"
  state :streaming_progress, description: "Streaming progress update"
  state :complete,          description: "Execution completed successfully"
  state :failed,            description: "Execution failed"

  # Define state transitions
  transition from: :pending, to: :running, on: :start
  transition from: :running, to: :executing, on: :initialized
  transition from: :executing, to: :evaluating, on: :executed
  transition from: :evaluating, to: :executing, on: :continue
  transition from: :evaluating, to: :checkpoint_created, on: :checkpoint
  transition from: :checkpoint_created, to: :executing, on: :next_milestone
  transition from: :checkpoint_created, to: :complete, on: :finish
  transition from: [:executing, :evaluating], to: :error_recovery, on: :error
  transition from: :error_recovery, to: :executing, on: :recovered
  transition from: :error_recovery, to: :failed, on: :fail
  transition from: [:executing, :evaluating, :checkpoint_created], to: :streaming_progress, on: :stream
  transition from: :streaming_progress, to: :executing, on: :resume
  transition from: :failed, to: :pending, on: :retry

  # Approval modes
  APPROVAL_MODES = [
    AUTONOMOUS = :autonomous,    # No approvals required (default)
    STEP = :step,               # Approve each step
    MILESTONE = :milestone      # Approve each milestone
  ].freeze

  attr_reader :execution_plan, :config, :memory_store,
              :current_milestone_index, :current_step_index,
              :execution_record, :progress_stream

  # Initialize SisyphusWorker with execution plan and configuration
  #
  # @param execution_plan [Planning::ExecutionPlan] The plan to execute
  # @param path [String] The codebase root directory
  # @param context [Hash] Optional context information
  # @param config [Hash] Configuration options
  # @option config [Symbol] :approval_mode (:autonomous, :step, :milestone)
  # @option config [Integer] :max_retries (3) Maximum retry attempts per step
  # @option config [Boolean] :stream_progress (true) Enable SSE progress streaming
  # @option config [Symbol] :error_mode (:lenient) Error handling mode (:strict, :lenient, :interactive)
  def initialize(execution_plan:, path:, context: {}, config: {})
    # Validate execution_plan
    unless execution_plan.is_a?(Planning::Result)
      raise TypeError, "execution_plan must be a Planning::Result, got #{execution_plan.class}"
    end

    # Initialize parent with synthesized goal from plan
    super(
      goal: execution_plan.goal,
      path: path,
      context: context
    )

    @execution_plan = execution_plan
    @config = build_config(config)
    @current_milestone_index = 0
    @current_step_index = 0
    @execution_record = nil
    @progress_stream = nil
    @checkpoint_service = nil
    @diff_service = nil

    validate_config!
  end

  # Execute the complete execution plan
  # Iterates through milestones and steps, executing each with full pipeline:
  # context assembly → planning → validation → execution → evaluation
  #
  # @return [Hash] Execution result with record, checkpoints, and logs
  def execute
    trigger(:start)
    initialize_execution

    trigger(:initialized)
    execute_all_milestones

    result = build_result
    trigger(:finish)

    # Update metadata with final state after transition
    result[:metadata][:final_state] = current_state
    result
  rescue StandardError => e
    handle_execution_error(e)
  end

  # Get current milestone being executed
  # @return [Planning::Milestone, nil]
  def current_milestone
    return nil if @current_milestone_index >= @execution_plan.milestones.size
    @execution_plan.milestones[@current_milestone_index]
  end

  # Get current step being executed
  # @return [Planning::Step, nil]
  def current_step
    milestone = current_milestone
    return nil unless milestone
    return nil if @current_step_index >= milestone.steps.size
    milestone.steps[@current_step_index]
  end

  # Calculate execution progress percentage
  # @return [Float] Progress from 0.0 to 100.0
  def progress_percentage
    return 0.0 if @execution_plan.milestones.empty?

    total_steps = @execution_plan.step_count
    return 0.0 if total_steps.zero?

    completed = 0
    @execution_plan.milestones.each_with_index do |milestone, m_idx|
      if m_idx < @current_milestone_index
        # Previous milestones fully complete
        completed += milestone.step_count
      elsif m_idx == @current_milestone_index
        # Current milestone partially complete
        completed += @current_step_index
      end
    end

    (completed.to_f / total_steps * 100).round(2)
  end

  # Stream progress event via SSE
  # @param event_type [Symbol] Type of progress event
  # @param data [Hash] Event data
  def emit_progress(event_type, data = {})
    return unless @config[:stream_progress]
    return unless @progress_stream

    event = {
      event_type: event_type,
      timestamp: Time.now.utc.iso8601,
      data: data.merge(
        milestone: current_milestone&.title,
        step: current_step&.title,
        progress: progress_percentage
      )
    }

    @progress_stream << event
  end

  private

  # Build configuration with defaults
  def build_config(config)
    {
      approval_mode: config.fetch(:approval_mode, AUTONOMOUS),
      max_retries: config.fetch(:max_retries, 3),
      stream_progress: config.fetch(:stream_progress, true),
      error_mode: config.fetch(:error_mode, :lenient)
    }
  end

  # Validate configuration parameters
  def validate_config!
    unless APPROVAL_MODES.include?(@config[:approval_mode])
      raise ArgumentError, "Invalid approval_mode: #{@config[:approval_mode]}. " \
                           "Must be one of: #{APPROVAL_MODES.join(', ')}"
    end

    unless @config[:max_retries].is_a?(Integer) && @config[:max_retries] > 0
      raise ArgumentError, "max_retries must be a positive Integer, got #{@config[:max_retries]}"
    end

    unless [true, false].include?(@config[:stream_progress])
      raise ArgumentError, "stream_progress must be a Boolean, got #{@config[:stream_progress]}"
    end

    unless [:strict, :lenient, :interactive].include?(@config[:error_mode])
      raise ArgumentError, "Invalid error_mode: #{@config[:error_mode]}. " \
                           "Must be one of: strict, lenient, interactive"
    end
  end

  # Initialize execution environment
  def initialize_execution
    ensure_state_directory!
    @memory_store = create_memory_store
    @progress_stream = [] if @config[:stream_progress]

    record_decision(
      decision: "initialize_execution",
      reasoning: "Starting execution of plan: #{@execution_plan.goal}",
      evidence: {
        milestone_count: @execution_plan.milestone_count,
        step_count: @execution_plan.step_count,
        approval_mode: @config[:approval_mode]
      }
    )

    emit_progress(:execution_started, {
      goal: @execution_plan.goal,
      milestone_count: @execution_plan.milestone_count,
      step_count: @execution_plan.step_count
    })
  end

  # Execute all milestones in sequence
  def execute_all_milestones
    @execution_plan.milestones.each_with_index do |milestone, index|
      @current_milestone_index = index
      @current_step_index = 0

      emit_progress(:milestone_started, {
        milestone_number: milestone.number,
        milestone_title: milestone.title
      })

      execute_milestone(milestone)

      emit_progress(:milestone_completed, {
        milestone_number: milestone.number
      })
    end
  end

  # Execute a single milestone
  # @param milestone [Planning::Milestone]
  def execute_milestone(milestone)
    # TODO: Implement in Milestone 5
    # This will iterate through steps and execute each one
    record_decision(
      decision: "execute_milestone",
      reasoning: "Executing milestone: #{milestone.title}",
      evidence: { milestone_number: milestone.number, step_count: milestone.step_count }
    )
  end

  # Create memory store for this execution
  def create_memory_store
    WorkflowMemoryStore.new(
      owner_id: @owner_id,
      workflow_id: SecureRandom.uuid,
      workflow_name: self.class.worker_name
    )
  end

  # Record a decision to memory
  def record_decision(decision:, reasoning:, evidence: {})
    return unless @memory_store

    @memory_store.record_decision(
      decision: decision,
      rationale: reasoning,
      context: evidence.merge(source: self.class.worker_name)
    )
  end

  # Build final execution result
  def build_result
    {
      success: true,
      execution_plan_goal: @execution_plan.goal,
      execution_plan_name: @execution_plan.project_name,
      milestones_completed: @current_milestone_index,
      progress: progress_percentage,
      metadata: {
        worker_id: @owner_id,
        config: @config,
        started_at: Time.now.utc.iso8601
      }
    }
  end

  # Handle execution errors
  def handle_execution_error(error)
    Rails.logger.error "[SisyphusWorker] Execution error: #{error.message}"
    Rails.logger.error error.backtrace.first(10).join("\n")

    record_decision(
      decision: "execution_failed",
      reasoning: "Execution encountered fatal error: #{error.message}",
      evidence: { error_class: error.class.name, backtrace: error.backtrace.first(5) }
    )

    mark_failed(error.message)

    {
      success: false,
      error: error.message,
      error_class: error.class.name,
      milestone_index: @current_milestone_index,
      step_index: @current_step_index,
      metadata: {
        worker_id: @owner_id,
        final_state: current_state
      }
    }
  end
end

