# frozen_string_literal: true

# SisyphusWorker: Autonomous execution agent that executes structured plans step-by-step.
# Named after the Greek hero condemned to eternally push a boulder uphill, Sisyphus
# processes ExecutionPlan objects generated by PlanAgentWorker, executing actions,
# evaluating completion, and tracking all changes with Git checkpoints.
#
# Unlike Cline's synchronous approval model, Sisyphus operates autonomously by default
# but can be configured for step-by-step or milestone-by-milestone approval.
#
# @example Basic autonomous execution
#   worker = SisyphusWorker.new(
#     execution_plan: plan,
#     path: "/path/to/codebase",
#     config: { approval_mode: :autonomous }
#   )
#   result = worker.execute
#
# @example With step-by-step approval
#   worker = SisyphusWorker.new(
#     execution_plan: plan,
#     path: "/path/to/codebase",
#     config: { approval_mode: :step, max_retries: 3 }
#   )
#   result = worker.execute
#
class SisyphusWorker < BaseWorker
  # Sisyphus-specific states beyond base worker states
  initial_state :pending

  state :pending,           description: "Worker created, not yet started"
  state :running,           description: "Initializing execution"
  state :executing,         description: "Executing plan steps"
  state :evaluating,        description: "Evaluating step completion"
  state :checkpoint_created, description: "Created milestone checkpoint"
  state :error_recovery,    description: "Recovering from error"
  state :streaming_progress, description: "Streaming progress update"
  state :complete,          description: "Execution completed successfully"
  state :failed,            description: "Execution failed"

  # Define state transitions
  transition from: :pending, to: :running, on: :start
  transition from: :running, to: :executing, on: :initialized
  transition from: :executing, to: :evaluating, on: :executed
  transition from: :evaluating, to: :executing, on: :continue
  transition from: :evaluating, to: :checkpoint_created, on: :checkpoint
  transition from: :checkpoint_created, to: :executing, on: :next_milestone
  transition from: :checkpoint_created, to: :complete, on: :finish
  transition from: [:executing, :evaluating], to: :error_recovery, on: :error
  transition from: :error_recovery, to: :executing, on: :recovered
  transition from: :error_recovery, to: :failed, on: :fail
  transition from: [:executing, :evaluating, :checkpoint_created], to: :streaming_progress, on: :stream
  transition from: :streaming_progress, to: :executing, on: :resume
  transition from: :failed, to: :pending, on: :retry

  # Default configuration
  DEFAULT_CONFIG = Configuration::SisyphusConfig.new(
    approval_mode: :autonomous,
    max_retries: 3,
    stream_progress: true,
    error_mode: :lenient,
    dry_run: false
  ).freeze

  attr_reader :execution_plan, :config, :memory_store,
              :current_milestone_index, :current_step_index,
              :execution_record, :progress_stream, :checkpoint_service

  # Initialize SisyphusWorker with execution plan and configuration
  #
  # @param execution_plan [Planning::Result] The plan to execute
  # @param path [String] The codebase root directory
  # @param context [Contexts::BaseContext] Context object (REQUIRED)
  # @param config [Configuration::SisyphusConfig] Configuration object
  def initialize(execution_plan:, path:, context:, config: DEFAULT_CONFIG)
    raise TypeError, "execution_plan must be a Planning::Result, got #{execution_plan.class}" unless execution_plan.is_a?(Planning::Result)
    raise TypeError, "config must be a Configuration::SisyphusConfig, got #{config.class}" unless config.is_a?(Configuration::SisyphusConfig)

    # Initialize parent with synthesized goal from plan
    super(
      goal: execution_plan.goal,
      path: path,
      context: context
    )

    @execution_plan = execution_plan
    @config = config
    @current_milestone_index = 0
    @current_step_index = 0
    @execution_record = nil
    @progress_stream = nil
    @checkpoint_service = nil
    @diff_service = nil
  end

  # Execute the complete execution plan
  # Iterates through milestones and steps, executing each with full pipeline:
  # context assembly → planning → validation → execution → evaluation
  #
  # @return [Hash] Execution result with record, checkpoints, and logs
  def execute
    trigger(:start)
    initialize_execution

    trigger(:initialized)
    execute_all_milestones

    result = build_result
    trigger(:finish)

    # Update metadata with final state after transition
    result[:metadata][:final_state] = current_state
    result
  rescue StandardError => e
    handle_execution_error(e)
  end

  # Get current milestone being executed
  # @return [Planning::Milestone, nil]
  def current_milestone
    return nil if @current_milestone_index >= @execution_plan.milestones.size
    @execution_plan.milestones[@current_milestone_index]
  end

  # Get current step being executed
  # @return [Planning::Step, nil]
  def current_step
    milestone = current_milestone
    return nil unless milestone
    return nil if @current_step_index >= milestone.steps.size
    milestone.steps[@current_step_index]
  end

  # Calculate execution progress percentage
  # @return [Float] Progress from 0.0 to 100.0
  def progress_percentage
    return 0.0 if @execution_plan.milestones.empty?

    total_steps = @execution_plan.step_count
    return 0.0 if total_steps.zero?

    completed = 0
    @execution_plan.milestones.each_with_index do |milestone, m_idx|
      if m_idx < @current_milestone_index
        # Previous milestones fully complete
        completed += milestone.step_count
      elsif m_idx == @current_milestone_index
        # Current milestone partially complete
        completed += @current_step_index
      end
    end

    (completed.to_f / total_steps * 100).round(2)
  end

  # Stream progress event via SSE
  # @param event_type [Symbol] Type of progress event
  # @param data [Hash] Event data
  def emit_progress(event_type, data = {})
    return unless @config.stream_progress
    return unless @progress_stream

    event = {
      event_type: event_type,
      timestamp: Time.now.utc.iso8601,
      data: data.merge(
        milestone: current_milestone&.title,
        step: current_step&.title,
        progress: progress_percentage
      )
    }

    @progress_stream << event
  end

  private

  # Initialize execution environment
  def initialize_execution
    ensure_state_directory!
    @memory_store = create_memory_store
    @progress_stream = [] if @config.stream_progress
    
    # Initialize services (checkpoint service only if git repo exists)
    @checkpoint_service = initialize_checkpoint_service
    @diff_service = DiffGenerationService.new
    @output_service = ExecutionOutputService.new
    
    # Initialize execution record
    @execution_record = Execution::ExecutionRecord.new(
      plan_id: @execution_plan.id,
      step_results: [],
      started_at: Time.now.utc.iso8601,
      status: :running
    )

    record_decision(
      decision: "initialize_execution",
      reasoning: "Starting execution of plan: #{@execution_plan.goal}",
      evidence: {
        milestone_count: @execution_plan.milestone_count,
        step_count: @execution_plan.step_count,
        approval_mode: @config.approval_mode,
        checkpoint_service_available: @checkpoint_service.present?
      }
    )

    emit_progress(:execution_started, {
      goal: @execution_plan.goal,
      milestone_count: @execution_plan.milestone_count,
      step_count: @execution_plan.step_count
    })
    
    # Create initial checkpoint if available
    create_initial_checkpoint
  end
  
  # Initialize checkpoint service if git repository exists
  def initialize_checkpoint_service
    return nil unless File.directory?(File.join(@path, ".git"))
    
    CheckpointService.new(path: @path)
  rescue ArgumentError => e
    Rails.logger.warn "[SisyphusWorker] Checkpoint service unavailable: #{e.message}"
    nil
  end

  # Execute all milestones in sequence
  def execute_all_milestones
    @execution_plan.milestones.each_with_index do |milestone, index|
      @current_milestone_index = index
      @current_step_index = 0

      emit_progress(:milestone_started, {
        milestone_number: milestone.number,
        milestone_title: milestone.title
      })

      execute_milestone(milestone)

      emit_progress(:milestone_completed, {
        milestone_number: milestone.number
      })
    end
  end

  # Execute a single milestone
  # @param milestone [Planning::Milestone]
  def execute_milestone(milestone)
    record_decision(
      decision: "execute_milestone",
      reasoning: "Executing milestone: #{milestone.title}",
      evidence: { milestone_number: milestone.number, step_count: milestone.step_count }
    )
    
    # Execute each step in the milestone
    milestone.steps.each_with_index do |step, step_index|
      @current_step_index = step_index
      
      emit_progress(:step_started, {
        step_number: step.number,
        step_title: step.title
      })
      
      # Execute step with full pipeline
      step_result = execute_step(step)
      @execution_record.add_step_result(step_result)
      
      emit_progress(:step_completed, {
        step_number: step.number,
        success: step_result.successful?,
        files_changed: step_result.files_changed.size
      })
      
      # Handle step failure based on error mode
      handle_step_failure(step, step_result) if step_result.failed?
    end
    
    # Create checkpoint at milestone boundary
    create_milestone_checkpoint(milestone)
    
    # Mark milestone as completed in execution record
    @execution_record.mark_milestone_completed(milestone.number.to_s)
  end
  
  # Execute a single step with full 5-phase pipeline
  # @param step [Planning::Step]
  # @return [Execution::StepResult]
  def execute_step(step)
    retries = 0
    max_retries = @config.max_retries
    
    loop do
      begin
        trigger(:executing)
        
        # Create and setup execution workflow
        execution_workflow = StepExecutionWorkflow.new(
          owner_id: @owner_id,
          parent_memory: @memory_store
        )
        
        execution_workflow.setup(
          step: step,
          path: @path,
          context: @context,
          system_prompt: nil # TODO: Add SisyphusSystemPrompt in future iteration
        )
        
        # Execute with full pipeline
        execution_result = execution_workflow.execute
        
        # Build StepResult from execution
        step_result = build_step_result(step, execution_workflow, execution_result)
        
        # Evaluate step completion
        trigger(:evaluating)
        evaluation_result = evaluate_step(step, step_result)
        
        # Update step result with evaluation
        step_result = step_result.class.new(
          **step_result.to_h.merge(evaluation_result: evaluation_result)
        )
        
        # If evaluation passed or max retries reached, return result
        if evaluation_result[:passed] || retries >= max_retries
          return step_result
        end
        
        # Retry if evaluation failed and retries available
        retries += 1
        record_decision(
          decision: "retry_step",
          reasoning: "Step evaluation failed, retrying (attempt #{retries}/#{max_retries})",
          evidence: { step_number: step.number, evaluation: evaluation_result }
        )
        
      rescue StandardError => e
        # Handle execution error
        Rails.logger.error "[SisyphusWorker] Step execution error: #{e.message}"
        
        return build_error_step_result(step, e)
      end
    end
  end
  
  # Build StepResult from execution workflow
  # @param step [Planning::Step]
  # @param workflow [StepExecutionWorkflow]
  # @param execution_result [Hash]
  # @return [Execution::StepResult]
  def build_step_result(step, workflow, execution_result)
    # Generate diffs for changed files
    files_changed = workflow.tool_executions
      .select { |exec| exec[:tool] == "write_file" && exec[:success] }
      .map { |exec| exec[:params][:path] }
    
    diffs = generate_diffs_for_changes(files_changed)
    
    Execution::StepResult.new(
      step_id: step.number,
      success: execution_result[:success],
      actions_taken: workflow.tool_executions.map { |e| build_action_record(e) },
      files_changed: files_changed,
      diffs: diffs,
      tool_outputs: { execution_result: execution_result },
      duration: execution_result[:duration] || 0.0
    )
  end
  
  # Build ActionRecord from tool execution
  # @param execution [Hash]
  # @return [ActionRecord]
  def build_action_record(execution)
    ActionRecord.new(
      id: SecureRandom.uuid,
      action_type: execution[:tool],
      timestamp: Time.now.utc.iso8601,
      action_input: execution[:params],
      result: execution[:result],
      success: execution[:success]
    )
  end
  
  # Build error StepResult
  # @param step [Planning::Step]
  # @param error [StandardError]
  # @return [Execution::StepResult]
  def build_error_step_result(step, error)
    Execution::StepResult.new(
      step_id: step.number,
      success: false,
      actions_taken: [],
      files_changed: [],
      diffs: {},
      error_message: "#{error.class}: #{error.message}",
      duration: 0.0
    )
  end
  
  # Evaluate step completion
  # @param step [Planning::Step]
  # @param step_result [Execution::StepResult]
  # @return [Hash] Evaluation result
  def evaluate_step(step, step_result)
    evaluation_workflow = StepEvaluationWorkflow.new(
      owner_id: @owner_id,
      parent_memory: @memory_store
    )
    
    evaluation_workflow.setup(
      step: step,
      step_result: step_result,
      path: @path,
      system_prompt: nil
    )
    
    evaluation_workflow.execute
  rescue StandardError => e
    Rails.logger.error "[SisyphusWorker] Step evaluation error: #{e.message}"
    
    # Default to failed evaluation
    {
      passed: false,
      confidence: 0.0,
      feedback: "Evaluation failed: #{e.message}",
      missing_requirements: [],
      concerns: ["Evaluation error occurred"],
      should_retry: false
    }
  end
  
  # Generate diffs for changed files
  # @param file_paths [Array<String>]
  # @return [Hash] Diffs keyed by file path (diff_content strings)
  def generate_diffs_for_changes(file_paths)
    diffs = {}
    
    file_paths.each do |file_path|
      full_path = File.join(@path, file_path)
      
      # Read current content
      new_content = File.exist?(full_path) ? File.read(full_path) : nil
      
      # For now, we don't have old content stored
      # In a real implementation, we'd get this from git or cached state
      old_content = ""
      
      # Generate diff (returns FileDiff object)
      file_diff = @diff_service.generate_diff(
        file_path: file_path,
        old_content: old_content,
        new_content: new_content
      )
      
      # Store the diff content string
      diffs[file_path] = file_diff.diff_content
    rescue StandardError => e
      Rails.logger.warn "[SisyphusWorker] Failed to generate diff for #{file_path}: #{e.message}"
    end
    
    diffs
  end
  
  # Handle step failure based on error mode
  # @param step [Planning::Step]
  # @param step_result [Execution::StepResult]
  def handle_step_failure(step, step_result)
    case @config.error_mode
    when :strict
      # Abort on any failure
      raise StandardError, "Step #{step.number} failed: #{step_result.error_message}"
    when :lenient
      # Log and continue
      Rails.logger.warn "[SisyphusWorker] Step #{step.number} failed but continuing (lenient mode)"
      record_decision(
        decision: "continue_after_failure",
        reasoning: "Continuing execution despite step failure (lenient mode)",
        evidence: { step_number: step.number, error: step_result.error_message }
      )
    when :interactive
      # Would request user input in a real implementation
      Rails.logger.warn "[SisyphusWorker] Step #{step.number} failed (interactive mode not yet implemented)"
    end
  end
  
  # Create initial checkpoint before execution starts
  def create_initial_checkpoint
    return unless checkpoint_service_available?
    
    checkpoint = @checkpoint_service.create_checkpoint(
      "Execution start: #{@execution_plan.goal}",
      execution_id: @owner_id,
      milestone_id: "initial"
    )
    
    # Store in execution record
    @execution_record.add_checkpoint(checkpoint.id)
    
    # Store in memory with full metadata
    @memory_store.record_checkpoint(checkpoint)
    
    record_decision(
      decision: "initial_checkpoint_created",
      reasoning: "Created initial checkpoint before execution",
      evidence: { 
        checkpoint_id: checkpoint.id,
        short_id: checkpoint.short_id,
        files_changed: checkpoint.file_count
      }
    )
  rescue StandardError => e
    Rails.logger.warn "[SisyphusWorker] Failed to create initial checkpoint: #{e.message}"
    # Non-fatal - continue execution
  end
  
  # Create checkpoint at milestone boundary
  # @param milestone [Planning::Milestone]
  def create_milestone_checkpoint(milestone)
    return unless checkpoint_service_available?
    
    trigger(:checkpoint)
    
    checkpoint = @checkpoint_service.create_checkpoint(
      "#{milestone.title} - Complete",
      milestone_id: milestone.number.to_s,
      execution_id: @owner_id,
      step_ids: milestone.steps.map(&:number)
    )
    
    # Store in execution record
    @execution_record.add_checkpoint(checkpoint.id)
    
    # Store in memory with full metadata
    @memory_store.record_checkpoint(checkpoint)
    
    emit_progress(:checkpoint_created, {
      milestone_number: milestone.number,
      checkpoint_id: checkpoint.id,
      short_id: checkpoint.short_id,
      files_changed: checkpoint.file_count
    })
    
    record_decision(
      decision: "milestone_checkpoint_created",
      reasoning: "Created checkpoint for milestone: #{milestone.title}",
      evidence: { 
        milestone_number: milestone.number,
        checkpoint_id: checkpoint.id,
        short_id: checkpoint.short_id,
        steps_completed: milestone.step_count,
        files_changed: checkpoint.file_count
      }
    )
    
    trigger(:next_milestone)
  rescue StandardError => e
    Rails.logger.error "[SisyphusWorker] Failed to create milestone checkpoint: #{e.message}"
    # Non-fatal - record error but continue
    record_decision(
      decision: "checkpoint_failed",
      reasoning: "Failed to create checkpoint: #{e.message}",
      evidence: { milestone_number: milestone.number, error: e.message }
    )
  end
  
  # Check if checkpoint service is available
  def checkpoint_service_available?
    @checkpoint_service.present?
  end

  # Create memory store for this execution
  def create_memory_store
    WorkflowMemoryStore.new(
      workflow_id: SecureRandom.uuid,
      workflow_name: self.class.worker_name,
      parent_id: "root",
      owner_id: @owner_id,
      path: File.join(@path, "sisyphus_memory.json")
    )
  end

  # Record a decision to memory
  def record_decision(decision:, reasoning:, evidence: {})
    return unless @memory_store

    @memory_store.record_decision(
      decision: decision,
      rationale: reasoning,
      context: evidence.merge(source: self.class.worker_name)
    )
  end

  # Build final execution result
  def build_result
    # Update execution record status
    if @execution_record
      @execution_record.update_status(:complete)
      
      # Write execution output
      begin
        output_result = @output_service.write_execution_output(
          @execution_record,
          plan_name: @execution_plan.project_name || "sisyphus_execution"
        )
        
        emit_progress(:output_written, {
          output_dir: output_result[:output_dir]
        })
      rescue StandardError => e
        Rails.logger.error "[SisyphusWorker] Failed to write execution output: #{e.message}"
      end
    end
    
    {
      success: true,
      execution_record: @execution_record,
      execution_plan_goal: @execution_plan.goal,
      execution_plan_name: @execution_plan.project_name,
      milestones_completed: @current_milestone_index + 1,
      progress: progress_percentage,
      checkpoint_ids: @execution_record&.checkpoint_ids || [],
      metadata: {
        worker_id: @owner_id,
        config: @config,
        started_at: @execution_record&.started_at || Time.now.utc.iso8601,
        completed_at: Time.now.utc.iso8601,
        final_state: nil # Will be set after state transition
      }
    }
  end

  # Handle execution errors
  def handle_execution_error(error)
    Rails.logger.error "[SisyphusWorker] Execution error: #{error.message}"
    Rails.logger.error error.backtrace.first(10).join("\n")

    record_decision(
      decision: "execution_failed",
      reasoning: "Execution encountered fatal error: #{error.message}",
      evidence: { error_class: error.class.name, backtrace: error.backtrace.first(5) }
    )

    # Safely transition to failed state
    begin
      # Try to transition through error_recovery if in a state that supports it
      if [:executing, :evaluating].include?(current_state)
        trigger(:error)
      end
      mark_failed(error.message)
    rescue StateMachine::InvalidTransition => e
      # If we can't transition, just log it and set failed state manually
      Rails.logger.warn "[SisyphusWorker] Could not transition to failed state: #{e.message}"
      @state = :failed
    end

    {
      success: false,
      error: error.message,
      error_class: error.class.name,
      milestone_index: @current_milestone_index,
      step_index: @current_step_index,
      metadata: {
        worker_id: @owner_id,
        final_state: current_state
      }
    }
  end
end

