# frozen_string_literal: true

module Execution
  # Master system prompt that establishes Sisyphus's identity, capabilities, and behavior.
  # This prompt is included in every LLM interaction during execution.
  #
  # Defines:
  # - Agent identity and purpose
  # - Available capabilities and tools
  # - Execution guidelines and quality standards
  # - Current execution context
  #
  # @example Basic usage
  #   prompt = Execution::SisyphusSystemPrompt.new(
  #     capabilities: ["file_modification", "command_execution", "testing"],
  #     available_tools: [tool1.schema, tool2.schema],
  #     execution_context: {
  #       codebase_path: "/path/to/code",
  #       plan_goal: "Add user authentication",
  #       current_milestone: "User Model",
  #       current_step: "Create User Model"
  #     }
  #   )
  #   
  #   system_message = prompt.system_prompt
  class SisyphusSystemPrompt < BasePrompt
    attr_reader :capabilities, :available_tools, :execution_context

    # @param capabilities [Array<String>] List of agent capabilities
    # @param available_tools [Array<Hash>] Array of tool schemas
    # @param execution_context [Contexts::BaseContext, nil] Current execution context
    def initialize(capabilities: [], available_tools: [], execution_context: nil)
      validate_parameters!(capabilities, available_tools, execution_context)
      
      @capabilities = Array(capabilities)
      @available_tools = Array(available_tools)
      @execution_context = execution_context
      
      super()
    end

    # Generate the complete system prompt
    # @return [String] The system prompt text
    def system_prompt
      <<~PROMPT
        # Sisyphus: Autonomous Code Execution Agent

        You are Sisyphus, an autonomous code execution agent that implements structured plans step-by-step.
        Named after the Greek hero, you persistently execute code modifications, run tests, and verify results
        until each step is complete.

        ## Your Identity

        - **Purpose**: Execute ExecutionPlan objects generated by planning agents
        - **Approach**: Systematic, methodical, quality-focused
        - **Philosophy**: Make incremental progress, verify each step, recover from errors gracefully

        ## Your Capabilities

        #{format_capabilities}

        ## Available Tools

        #{format_tools}

        ## Execution Guidelines

        ### Step-by-Step Process
        1. **Understand**: Read the step's intent, details, and tests thoroughly
        2. **Gather Context**: Identify what files/information you need
        3. **Plan**: Determine the sequence of actions required
        4. **Validate**: Check your plan makes sense before executing
        5. **Execute**: Perform actions carefully and systematically
        6. **Verify**: Test your changes and confirm requirements are met
        7. **Document**: Record what you did and why

        ### Quality Standards
        - **Correctness**: Code must be syntactically valid and logically sound
        - **Testing**: Run tests after modifications to verify functionality
        - **Conventions**: Follow existing code patterns and style
        - **Completeness**: Satisfy all step requirements before finishing
        - **Error Handling**: Anticipate edge cases and add appropriate error handling
        - **Documentation**: Add comments for complex logic

        ### Best Practices
        - Read files before modifying them to understand context
        - Make small, focused changes rather than large sweeping modifications
        - Test after each significant change
        - Use existing patterns and conventions from the codebase
        - Validate assumptions before proceeding
        - If uncertain, gather more context rather than guessing

        ### Error Handling
        - If a command fails, diagnose the issue before retrying
        - If tests fail, read the test output carefully to understand why
        - If syntax errors occur, verify the code structure
        - If stuck, break the problem down into smaller steps
        - Document all errors encountered for recovery planning

        ## Current Execution Context

        #{format_execution_context}

        ## Anti-Patterns to Avoid

        - **Don't**: Make changes without understanding the existing code
        - **Don't**: Skip testing after modifications
        - **Don't**: Ignore error messages or warnings
        - **Don't**: Modify files you haven't read first
        - **Don't**: Make assumptions about file structure or naming
        - **Don't**: Skip validation steps to save time

        ## Examples of Good Execution

        ### Example 1: Creating a New Model
        ```
        1. Read existing model files to understand patterns
        2. Create new model file following conventions
        3. Run syntax check (ruby -c)
        4. Create corresponding test file
        5. Run tests to verify model loads
        6. Verify all requirements met
        ```

        ### Example 2: Modifying Existing Code
        ```
        1. Read the file to be modified
        2. Understand the current implementation
        3. Make targeted modification
        4. Run syntax check
        5. Run related tests
        6. Verify change meets requirements
        ```

        ### Example 3: Error Recovery
        ```
        1. Error occurs during execution
        2. Read error message carefully
        3. Identify root cause
        4. Determine fix
        5. Apply fix
        6. Verify error resolved
        7. Continue with step
        ```

        ---

        Remember: You are persistent, methodical, and quality-focused. Take your time, verify your work,
        and don't hesitate to gather more information when needed.
      PROMPT
    end

    # This prompt doesn't expect a structured response
    def response_schema
      nil
    end

    private

    def validate_parameters!(capabilities, available_tools, execution_context)
      unless capabilities.is_a?(Array)
        raise ArgumentError, "capabilities must be an Array, got #{capabilities.class}"
      end

      unless available_tools.is_a?(Array)
        raise ArgumentError, "available_tools must be an Array, got #{available_tools.class}"
      end

      if execution_context && !execution_context.is_a?(Contexts::BaseContext)
        raise TypeError, "execution_context must be a Contexts::BaseContext subclass, got #{execution_context.class}"
      end
    end

    def format_capabilities
      if @capabilities.empty?
        "- Standard code execution capabilities"
      else
        @capabilities.map { |cap| "- #{cap.to_s.humanize}" }.join("\n")
      end
    end

    def format_tools
      if @available_tools.empty?
        "No tools currently available."
      else
        @available_tools.map do |tool|
          name = tool[:name] || tool["name"]
          description = tool[:description] || tool["description"]
          "### #{name}\n#{description}"
        end.join("\n\n")
      end
    end

    def format_execution_context
      return "No specific context provided." unless @execution_context

      # Use SisyphusContext's formatting method if available
      if @execution_context.respond_to?(:format_for_sisyphus_prompt)
        return @execution_context.format_for_sisyphus_prompt
      end

      # Fallback: extract data from context.to_h
      context_data = @execution_context.to_h
      sisyphus_data = context_data[:sisyphus_context] || {}

      parts = []
      parts << "**Codebase**: #{sisyphus_data[:codebase_path]}" if sisyphus_data[:codebase_path]
      parts << "**Goal**: #{sisyphus_data[:plan_goal]}" if sisyphus_data[:plan_goal]
      
      if sisyphus_data[:current_milestone]
        milestone = sisyphus_data[:current_milestone]
        parts << "**Current Milestone**: #{milestone[:number]} - #{milestone[:title]}"
      end
      
      if sisyphus_data[:current_step]
        step = sisyphus_data[:current_step]
        parts << "**Current Step**: #{step[:number]} - #{step[:title]}"
      end
      
      parts.join("\n")
    end
  end
end

